name: Terraform CI

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Init
      run: terraform init

    - name: Validate
      run: terraform validate

    - name: Plan
      run: terraform plan

    - name: Apply (Manual)
      run: echo "Run terraform apply manually"
